### ISSUE TITLE
Make landing page for the new OSPAR assessment tool

### ISSUE THREAD

**Issue by HansMJ** [ices-taf/OHAT#10]
The landing page should look similar to the IROC page:
http://www.ices.dk/marine-data/data-portals/Pages/iroc.aspx 

Not certian about the title name. So far the suggestion is OSPAR hazardous assessment tool OHAT 

A short summary text describing the MIME assessment and then a link to the assessment tool. Also a link to the OSPAR page:
https://www.ospar.org/news/working-group-on-monitoring-and-on-trends-and-effects-of-substances-in-the-marine-environment-mime

**Comment by neil-ices-dk** [comment]
Ospar Conatimants Assessment Tool (OCAT)

**Comment by neil-ices-dk** [comment]
ok, i have created the landing page, the link you won't be able to see until i publish; i've taken some text from OSPAR but we will need to get them to look over the page, which we should do once the app page is linked to it (next job) http://ices.dk/marine-data/assessment-tools/Pages/ospar-cat.aspx 
![image](https://user-images.githubusercontent.com/23527005/59039770-b8884400-8875-11e9-91d0-b63f60991131.png)

**Comment by neil-ices-dk** [comment]
web app
http://ices.dk/marine-data/assessment-tools/Pages/ospar-cat-app.aspx

![image](https://user-images.githubusercontent.com/23527005/59091649-0f425c00-8910-11e9-9ff3-d2e9600a40af.png)

@HansMJ to make drop-downs inline on Assessment and Stations tab
