### ISSUE TITLE
Make TAF controller webservice as POST

### ISSUE THREAD

**Issue by HansMJ** [ices-taf/OHAT#22]
Make TAF controller web service a POST so that series, compartment etc are passed as body arguments
class for POST body:
- string series
- string compartment
- int year

After creation in TAF the current GET request to TAF in the AHAT/OHAT/HHAT should be changed to a POST request 

This will solve the endless problems when passing spacial characters '%', '/' in the series ID

**Comment by colinpmillar** [comment]
Here is the object the service is expecting as the body:
```c#
  public class ContaminantsAssessmentDto
  {
    public string Series { get; set; } 
    public string Compartment { get; set; }
    public int Year { get; set; }
  }
```

**Comment by HansMJ** [comment]
Great, that seems right. Did you already enable the post service?

**Comment by colinpmillar** [comment]
Something like this should work on your side:
```c#
      var json = JsonConvert.SerializeObject(new ContaminantsAssessmentDto { Series = "", Compartment = "", Year = 2020 });
      var body new StringContent(json, Encoding.UTF8, "application/json");

      var resp = await client.PostAsync(url, body);
```

**Comment by colinpmillar** [comment]
yes I just published it :)   so ready to test

**Comment by HansMJ** [comment]
Thanks Colin, I will dive into it
