### ISSUE TITLE
Queue watcher fix

### ISSUE THREAD

**Issue by HansMJ** [ices-taf/OHAT#23]
Sort out the queue watcher - it falls over when null are passes as arguments from another queue user

Result is that 500 response is returned from  OHAT/AHAT/HHAT

**Comment by colinpmillar** [comment]
Fixed in recent commit.  Fix was easy in the end, the second string conversion needed a check for a null

```c#
public string[] Arguments_array =>
      JsonConvert.DeserializeObject<string[]>(Arguments).
      Select(s => s == null ? null : JsonConvert.DeserializeObject<string>(s))
      .ToArray();
```

**Comment by colinpmillar** [comment]
Actually @HansMJ could you test this for me? Let me know when and I will restart a smardots job
