### ISSUE TITLE
 2022 assessment preparations/issues

### ISSUE THREAD

**Issue by HansMJ** [ices-taf/OHAT#25]
- [ ] Prepare new raw data extraction incl. French Med data. Needs to clarify how Frech Med data are flagged (MPROG) and how they match with Station Dictionary (same as for OSPAR data but different MPROG?) - Pending data submission from France 
- [x] Ensure grade and stage are used interchangeably in fish disease extraction
- [x] Extract Danish sediment and biota data from Roskilde and Isefjord (outside Region 2, but regarded as Region 2 stations for QSR) 

[Raw data extractions](https://www.dropbox.com/sh/ap5piyr994rxbga/AABcFyV70ax8UxZsQO6a0Gm3a?dl=0)

**Comment by HansMJ** [comment]
@RobFryer I have now added 'ST' (stage) as an allowed MUNIT interchangeable with 'GRADE'. Perhaps I should do a test extraction now?

**Comment by HansMJ** [comment]
@RobFryer 
About the stations from Roskilde Fjord and Isefjord
Data has not been flagged for OSPAR when submitted, so they do not get included to the assessment extraction at present:
Last year Martin send me a list station with Mollusc data and sediment stations that should be included from Roskilde and Isefjord
[Roskilde-Isefjord stationer DK 2010-19.xlsx](https://github.com/ices-taf/OHAT/files/7075451/Roskilde-Isefjord.stationer.DK.2010-19.xlsx)
The station names mentioned (MC-stationsnr) are from the national Danish database and they can therefore vary from what has been reported to ICES. So I think I need to send Martin an overview of stations that has been submitted to ICES, so that he can identify what should be included from Isefjord and Roskilde fjord. I do not know if it can be trusted that all of these stations are in the station dictionary, in any case they are not flagged as OSPAR stations, because they are outside the OSPAR definition. When mapping stations the rule is that the stations from Station Dictionary should be flagged for OSPAR (or AMAP). So we would need to do some specific rules for the danish data to get the station data grouped together.

**Comment by RobFryer** [comment]
> @RobFryer I have now added 'ST' (stage) as an allowed MUNIT interchangeable with 'GRADE'. Perhaps I should do a test extraction now?

@HansMJ
Yes, that would be a good idea whilst it is still fresh in our minds.  I can then run the code on the data and check the UK data are appearing.  

@Osanna123 
Have Germany submitted any more fish disease data?  I know they were having some difficulties with their national database.

**Comment by RobFryer** [comment]
@HansMJ 
> About the stations from Roskilde Fjord and Isefjord
I don't think we should compromise the integrity of the database or the station dictionary by altering any data or station information so that it appears that the data are from Region 2.  If Martin has submitted the data to ICES (albeit without the OSPAR flag) with station names that are in the Station Dictionary, then is the best thing to do simply to add an extra rule to extract data from the identified Roskilde Fjord and Isefjord stations and I can then pick them up in the ad-hoc edits I make and map them to Region 2?
Do you know if this is only to be done for the QSR or will it be ongoing?  If the latter, then we would need something less ad-hoc.  Are there plans to extend OSPAR Region 2 more formally in to include Roskilde Fjord and Isefjord?  
Is there anything I should be doing at this stage on this topic?

**Comment by HansMJ** [comment]
@RobFryer 
You do not need to do anything at this stage. I will check with Martin on how the stations can be identified, so that I can extract them. I am not aware of any talks about adding Roskilde fjord and Isefjord waters as an extension to Region 2. Personally I think that would make good sense, but it is not my decision of course. I will aks Martin about this and also if this is considered a one off exception for the QSR or an ongoing addition when I get hold of him

**Comment by HansMJ** [comment]
> @RobFryer I have now added 'ST' (stage) as an allowed MUNIT interchangeable with 'GRADE'. Perhaps I should do a test extraction now?


> @HansMJ
> Yes, that would be a good idea whilst it is still fresh in our minds. I can then run the code on the data and check the UK data are appearing.

@RobFryer 
Here is a fresh fish disease extraction where both grade and stage are allowed. As far as I can see the more recent UK data are now included, but you can have a look at it:
[https://www.dropbox.com/sh/rmt89e17e4777cs/AADHpvWfsS13EJDdIlIIZudza?dl=0](https://www.dropbox.com/sh/rmt89e17e4777cs/AADHpvWfsS13EJDdIlIIZudza?dl=0)

**Comment by RobFryer** [comment]
> > @RobFryer I have now added 'ST' (stage) as an allowed MUNIT interchangeable with 'GRADE'. Perhaps I should do a test extraction now?
> 
> > @HansMJ
> > Yes, that would be a good idea whilst it is still fresh in our minds. I can then run the code on the data and check the UK data are appearing.
> 
> @RobFryer
> Here is a fresh fish disease extraction where both grade and stage are allowed. As far as I can see the more recent UK data are now included, but you can have a look at it:
> https://www.dropbox.com/sh/rmt89e17e4777cs/AADHpvWfsS13EJDdIlIIZudza?dl=0

@HansMJ 
The header to the file seems to be missing.  I am going to copy across the column names from the 2021 extraction and check the rest works (assuming the columns are in the same order).

**Comment by RobFryer** [comment]
@HansMJ 
Rest of the FDI extractions looks good :)  Have run it through Werner's code and have UK data each year until 2020 as expected.

**Comment by HansMJ** [comment]
> 
> 
> @HansMJ
> Rest of the FDI extractions looks good :) Have run it through Werner's code and have UK data each year until 2020 as expected.

@RobFryer 
That sounds good Rob. It is strange with the missing header, I cannot figure out why the it does not get included when I save it. It does for all other datasets. I will have to find a solution for that. It should be same header as last time as you figured out :)
