### ISSUE TITLE
Biota menus - repopulating maps

### ISSUE THREAD

**Issue by RobFryer** [ices-taf/OHAT#27]
There are an increasing number of drop-down menus for biota and it is getting harder to move between different selections without starting the selection afresh.  It would be good to review and streamline.

**Comment by HansMJ** [comment]
Just doing some cleaning up in the reported Issues for OHAT and wonder if this is still relevant. Or perhaps this is something that should be solved under implementing the dynamic structure (menu1, menu2, menu3).
I close the issue now, but let me know if it needs to be reopened
